const base = [
  {
    email: 'a@a.com',
    title: 'Семён Петрович Тихомиров',
    subtitle:
      'http://www.businesspravo.ru/Docum/DocumShow_DocumID_161069.html.',
    location: 'Москва, ул. Ленина,13',
    money: Number(10000),
    payOn: true,
    inviteAccepted: false,
  },
  {
    email: 'a@a.com',
    title: 'Аихомиров',
    subtitle: 'Всероссийся 2010 года на ... Город Цупаров',
    location: 'Пермь, ул. Ленина,13',
    money: Number(20000),
    payOn: true,
    inviteAccepted: false,
  },
  {
    email: 'a@a.com',
    title: 'Андрей Петрович Тихомиров',
    subtitle: 'Вд Цупаров',
    location: 'Пермь, ул. Ленина,13',
    money: Number(20000),
    payOn: true,
    inviteAccepted: false,
  },
  {
    email: 'b@b.com',
    title: 'Qaaaa',
    subtitle: 'Всероссийской переписи населения 2010 года на ... Город Цупаров',
    location: 'Перм,13',
    money: Number(20000),
    payOn: true,
    inviteAccepted: false,
  },
  {
    email: 'b@b.com',
    title: 'Qaaaa',
    subtitle: 'Всероссийской переписи населения 2010 года на ... Город Цупаров',
    location: 'Пермь, ул. Ленина,13',
    money: Number(0),
    payOn: false,
    inviteAccepted: false,
  },
  {
    email: 'c@c.com',
    title: 'Алекс',
    subtitle: 'Надо помочь',
    location: 'Екеатеринбург, ул. Ленина,13',
    money: Number(20000),
    payOn: true,
    inviteAccepted: true,
  },
  {
    email: 'c@c.com',
    title: 'Алексtyuio',
    subtitle: 'Надо ftryfguhiojpпомочь',
    location: 'Еyftugihopoкеатеринбург, ул. Ленина,13',
    money: Number(20000),
    payOn: true,
    inviteAccepted: true,
  },
];

export default base;
